name: Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build'
        required: true
        default: 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.12]
    
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.inputs.tag }}
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pybind11==2.11.0 pybind11-global==2.11.0 wheel
        
    - name: Configure CMake
      run: cmake -S . -B build -DPYBIND11_PYTHON_VERSION=${{ matrix.python-version }}
      
    - name: Build
      run: cmake --build build --config Release
      
    - name: Build Python Wheel
      run: |
        python setup.py bdist_wheel
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: python-wheel-${{ matrix.os }}-${{ matrix.python-version }}
        path: dist/*.whl

