name: Deploy Docs

on:
  push:
    branches:
      - main
      - Document
  workflow_dispatch:

concurrency:
  group: docs-deploy
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies (EN + ZH)
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/en/requirements.txt -r docs/zh/requirements.txt

      - name: Build English docs (root)
        run: sphinx-build -b html docs/en _site

      - name: Build Chinese docs (zh subdir)
        run: sphinx-build -b html docs/zh _site/zh

      - name: Create 404 redirect (optional)
        run: |
          echo '<meta http-equiv="refresh" content="0; url=index.html" />' > _site/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: _site
          keep_files: false
          force_orphan: false

# Root will serve English index.html by default; Chinese docs under /zh/.